name: Auto Update KBS

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install playwright
          playwright install chromium
          playwright install-deps

      - name: Run Scraper with XVFB
        run: xvfb-run python update_kbs.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "Tiada perubahan dikesan."
          else
            git commit -m "Auto-update KBS token link"
            git push
          fi
